"""Supplier directory tests — model validation, endpoints, persistence.

Every value asserted here comes from CONTEXT.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def client(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> TestClient:
    """Point TinyDB at a throwaway file so tests never touch real data."""
    monkeypatch.setenv("TINYDB_PATH", str(tmp_path / "test.json"))

    import database

    database.close_db()

    from main import app

    with TestClient(app) as c:
        yield c

    database.close_db()


@pytest.fixture
def seeded(client: TestClient) -> TestClient:
    import seed

    seed.seed()
    return client


VALID = {
    "name": "Correos Express",
    "country": "Spain",
    "categories": ["carrier_last_mile"],
    "rate_per_shipment": 4.10,
    "currency": "EUR",
    "status": "active",
}


# ---------------------------------------------------------------------------
# Model + validation
# ---------------------------------------------------------------------------


def test_create_returns_complete_object_with_id(client: TestClient) -> None:
    r = client.post("/suppliers", json=VALID)
    assert r.status_code == 201
    body = r.json()
    assert body["id"] >= 1
    assert body["name"] == "Correos Express"
    assert body["country"] == "Spain"
    assert body["categories"] == ["carrier_last_mile"]
    assert body["rate_per_shipment"] == 4.10
    assert body["currency"] == "EUR"
    assert body["status"] == "active"
    # updated_at is system-generated, never sent by the client.
    assert body.get("updated_at")


def test_updated_at_is_ignored_if_client_sends_it(client: TestClient) -> None:
    """CONTEXT: updated_at is generated by the system, not the client."""
    r = client.post(
        "/suppliers", json={**VALID, "updated_at": "1999-01-01T00:00:00+00:00"}
    )
    assert r.status_code == 201
    assert not r.json()["updated_at"].startswith("1999")


@pytest.mark.parametrize("bad_status", ["pending", "ACTIVE", "", "deleted"])
def test_status_outside_the_allowed_set_is_422(
    client: TestClient, bad_status: str
) -> None:
    r = client.post("/suppliers", json={**VALID, "status": bad_status})
    assert r.status_code == 422


@pytest.mark.parametrize("bad_rate", [0, -1, -0.01])
def test_zero_or_negative_rate_is_422(client: TestClient, bad_rate: float) -> None:
    r = client.post("/suppliers", json={**VALID, "rate_per_shipment": bad_rate})
    assert r.status_code == 422


def test_invalid_category_is_422(client: TestClient) -> None:
    r = client.post("/suppliers", json={**VALID, "categories": ["not_a_category"]})
    assert r.status_code == 422


def test_empty_categories_is_422(client: TestClient) -> None:
    r = client.post("/suppliers", json={**VALID, "categories": []})
    assert r.status_code == 422


def test_missing_required_country_is_422(client: TestClient) -> None:
    payload = {k: v for k, v in VALID.items() if k != "country"}
    r = client.post("/suppliers", json=payload)
    assert r.status_code == 422


def test_currency_must_match_country(client: TestClient) -> None:
    """CONTEXT § Business constraints: USA→USD, Spain→EUR."""
    r = client.post("/suppliers", json={**VALID, "country": "USA"})  # still EUR
    assert r.status_code == 422
    assert "currency" in json.dumps(r.json()).lower()

    ok = client.post(
        "/suppliers",
        json={**VALID, "name": "US Co", "country": "USA", "currency": "USD"},
    )
    assert ok.status_code == 201


def test_dual_category_carrier_is_valid(client: TestClient) -> None:
    """CONTEXT: a carrier may be both last-mile and international."""
    r = client.post(
        "/suppliers",
        json={
            **VALID,
            "name": "DHL Test",
            "categories": ["carrier_last_mile", "carrier_international"],
        },
    )
    assert r.status_code == 201
    assert r.json()["categories"] == ["carrier_last_mile", "carrier_international"]


def test_all_eight_context_categories_are_accepted(client: TestClient) -> None:
    categories = [
        "carrier_last_mile",
        "carrier_international",
        "warehouse_supplies",
        "packaging_materials",
        "reverse_logistics",
        "fleet_maintenance",
        "it_and_wms_software",
        "cleaning_and_facilities",
    ]
    for i, category in enumerate(categories):
        r = client.post(
            "/suppliers",
            json={**VALID, "name": f"Supplier {i}", "categories": [category]},
        )
        assert r.status_code == 201, f"{category} rejected"


# ---------------------------------------------------------------------------
# Seeder
# ---------------------------------------------------------------------------


def test_seeder_loads_all_fifteen_context_suppliers(client: TestClient) -> None:
    import seed

    inserted, skipped = seed.seed()
    assert inserted == 15
    assert skipped == 0
    assert len(client.get("/suppliers").json()) == 15


def test_seeder_is_idempotent(client: TestClient) -> None:
    import seed

    seed.seed()
    inserted, skipped = seed.seed()
    assert inserted == 0
    assert skipped == 15
    assert len(client.get("/suppliers").json()) == 15


def test_seeded_data_matches_context_values(seeded: TestClient) -> None:
    suppliers = {s["name"]: s for s in seeded.get("/suppliers").json()}
    ups = suppliers["UPS Ground"]
    assert ups["rate_per_shipment"] == 7.45
    assert ups["currency"] == "USD"
    assert ups["service_zone"] == "West Coast"

    # Two suppliers are suspended in the CONTEXT data.
    suspended = [s for s in suppliers.values() if s["status"] == "suspended"]
    assert {s["name"] for s in suspended} == {"Laser Ship", "SAP WM Cloud"}


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


def test_get_all_with_no_params_returns_everything(seeded: TestClient) -> None:
    assert len(seeded.get("/suppliers").json()) == 15


def test_filter_by_country(seeded: TestClient) -> None:
    usa = seeded.get("/suppliers", params={"country": "USA"}).json()
    spain = seeded.get("/suppliers", params={"country": "Spain"}).json()
    assert len(usa) == 9
    assert len(spain) == 6
    assert all(s["country"] == "USA" for s in usa)
    assert all(s["country"] == "Spain" for s in spain)


def test_filter_by_category(seeded: TestClient) -> None:
    r = seeded.get("/suppliers", params={"category": "reverse_logistics"})
    assert r.status_code == 200
    names = {s["name"] for s in r.json()}
    assert names == {"Logística Inversa Iberia", "ReturnBear"}


def test_filter_by_category_matches_dual_category_carriers(
    seeded: TestClient,
) -> None:
    r = seeded.get("/suppliers", params={"category": "carrier_international"})
    names = {s["name"] for s in r.json()}
    assert names == {"DHL Express USA", "DHL Express España"}


def test_filters_combine(seeded: TestClient) -> None:
    """'What last-mile carriers do we have in Spain?'"""
    r = seeded.get(
        "/suppliers", params={"country": "Spain", "category": "carrier_last_mile"}
    )
    names = {s["name"] for s in r.json()}
    assert names == {"MRW España", "SEUR", "DHL Express España", "Nacex"}


def test_unknown_filter_value_is_422(seeded: TestClient) -> None:
    assert seeded.get("/suppliers", params={"country": "France"}).status_code == 422
    assert seeded.get("/suppliers", params={"category": "nope"}).status_code == 422


def test_get_by_id(seeded: TestClient) -> None:
    first = seeded.get("/suppliers").json()[0]
    r = seeded.get(f"/suppliers/{first['id']}")
    assert r.status_code == 200
    assert r.json()["name"] == first["name"]


def test_get_by_id_404(client: TestClient) -> None:
    r = client.get("/suppliers/9999")
    assert r.status_code == 404
    assert "9999" in r.json()["detail"]


def test_patch_rate_updates_value_and_timestamp(seeded: TestClient) -> None:
    supplier = seeded.get("/suppliers").json()[0]
    before = supplier["updated_at"]

    r = seeded.patch(
        f"/suppliers/{supplier['id']}/rate", json={"rate_per_shipment": 9.99}
    )
    assert r.status_code == 200
    body = r.json()
    assert body["rate_per_shipment"] == 9.99
    # CONTEXT: every rate update records updated_at.
    assert body["updated_at"] >= before


@pytest.mark.parametrize("bad_rate", [0, -5])
def test_patch_rate_rejects_non_positive(seeded: TestClient, bad_rate: float) -> None:
    supplier = seeded.get("/suppliers").json()[0]
    r = seeded.patch(
        f"/suppliers/{supplier['id']}/rate", json={"rate_per_shipment": bad_rate}
    )
    assert r.status_code == 422


def test_patch_rate_404(client: TestClient) -> None:
    r = client.patch("/suppliers/9999/rate", json={"rate_per_shipment": 5})
    assert r.status_code == 404


def test_patch_status_activate_and_suspend(seeded: TestClient) -> None:
    supplier = seeded.get("/suppliers").json()[0]

    r = seeded.patch(f"/suppliers/{supplier['id']}/status", json={"status": "suspended"})
    assert r.status_code == 200
    assert r.json()["status"] == "suspended"

    r = seeded.patch(f"/suppliers/{supplier['id']}/status", json={"status": "active"})
    assert r.status_code == 200
    assert r.json()["status"] == "active"


@pytest.mark.parametrize("bad", ["deleted", "ACTIVE", "on-hold", ""])
def test_patch_status_rejects_disallowed_values(seeded: TestClient, bad: str) -> None:
    supplier = seeded.get("/suppliers").json()[0]
    r = seeded.patch(f"/suppliers/{supplier['id']}/status", json={"status": bad})
    assert r.status_code == 422


def test_patch_status_404(client: TestClient) -> None:
    r = client.patch("/suppliers/9999/status", json={"status": "active"})
    assert r.status_code == 404


def test_delete_removes_supplier(seeded: TestClient) -> None:
    supplier = seeded.get("/suppliers").json()[0]
    r = seeded.delete(f"/suppliers/{supplier['id']}")
    assert r.status_code == 200
    assert r.json()["deleted"] is True
    assert seeded.get(f"/suppliers/{supplier['id']}").status_code == 404
    assert len(seeded.get("/suppliers").json()) == 14


def test_delete_404(client: TestClient) -> None:
    r = client.delete("/suppliers/9999")
    assert r.status_code == 404


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------


def test_data_survives_a_server_restart(
    client: TestClient, tmp_path: Path
) -> None:
    """Cross-cutting: TinyDB persists — data is still there after a restart."""
    client.post("/suppliers", json=VALID)

    # It is really on disk, not just in memory.
    raw = json.loads((tmp_path / "test.json").read_text(encoding="utf-8"))
    assert any(
        row["name"] == "Correos Express" for row in raw["suppliers"].values()
    )

    # Simulate a restart: close the handle, build a fresh app + client.
    import database

    database.close_db()

    from main import app

    with TestClient(app) as fresh:
        names = {s["name"] for s in fresh.get("/suppliers").json()}
    assert "Correos Express" in names
